### PR TITLE
Disable "gap" prop on Stack when running in Chakra

### LINKED ISSUE #767: Assertion hit in `deepFreezeAndThrowOnMutationInDev` when navigating away from Separator page
While investigating a crash in the [PR migrating the Windows test app](https://github.com/microsoft/fluentui-react-native/pull/755) to `react-native-test-app`, I found that navigating away from the Separator page soft-crashes the test app on an assertion in `deepFreezeAndThrowOnMutationInDev`.

### Environment Information

- **Package version(s)**: `master`
- **OS version**: Windows 10 Enterprise 21H1 19043.1083

- **Platform**:
  - [ ] iOS
    - **Xcode version**:
  - [ ] macOS
    - **Xcode version**:
  - [ ] win32
  - [x] windows
  - [ ] android

### Please provide a reproduction of the bug:

1. Check out this branch: https://github.com/microsoft/fluentui-react-native/pull/755
2. Build and run windows test app
    ```sh
    yarn
    yarn build
    cd apps/windows
    yarn install-windows-test-app
    start windows/FluentTester.sln
    yarn start
    ```
3. Once the app starts, click on the Separator page, then navigate to any other page, e.g. Button

#### Actual behavior:

The test app soft-crashes in `deepFreezeAndThrowOnMutationInDev` and turns blank.

A workaround is to disable `gap`:

```diff
diff --git a/apps/fluent-tester/src/FluentTester/TestComponents/Separator/SeparatorTest.tsx b/apps/fluent-tester/src/FluentTester/TestComponents/Separator/SeparatorTest.tsx
index e0cf9e1b..18df01ba 100644
--- a/apps/fluent-tester/src/FluentTester/TestComponents/Separator/SeparatorTest.tsx
+++ b/apps/fluent-tester/src/FluentTester/TestComponents/Separator/SeparatorTest.tsx
@@ -11,8 +11,8 @@ const RedSeparator = Separator.customize({ color: 'red' });

 const separator: React.FunctionComponent<{}> = () => {
   return (
-    <Stack style={stackStyle} gap={5}>
-      <Stack gap={4} style={separatorStackStyle}>
+    <Stack style={stackStyle} gap={0}>
+      <Stack gap={0} style={separatorStackStyle}>
         <Button content="Button4" />
         <BlueSeparator vertical />
         <Button content="Button5" />
```

#### Expected behavior:

It doesn't soft-crash.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

### PR DESCRIPTION
**Pull request by rurikoaraki**
Fixes #767 

### Platforms Impacted
- [x] iOS
- [x] macOS
- [x] win32 (Office)
- [x] windows
- [x] android

### Description of changes

A workaround fix for an issue with Charka, RN, and Stack where we were seeing errors while running the RN Test App for Windows.

This issue seems to be a timing issue with using Chakra. While the code in the Stack component isn't inherently doing anything that isn't allowed by RN, it trips up a function which runs in debug bundles. We can't switch away from Chakra in UWP since the base test app, which we'll be switching to with #755, runs with Chakra and probably won't be using Hermes until 0.65. For now, we can disable the `gap` prop causing the issue in Chakra. Since Edge has switched to Chromium and RNW is trying to switch to Hermes, Chakra is less popular in usage so we think it's okay to not have the prop working when running Chakra.

I've tried other workarounds such as using Object.defineProperty directly, or using View components instead of marginTop/marginLeft to implement the spacing, to no avail. Short of removing the prop entirely, this is the best solution we have for this issue.

### Verification

Tested fix in UWP test app.

| Before                                       | After                                      |
|----------------------------------------------|--------------------------------------------|
| Screenshot or description before this change | Screenshot or description with this change |

### Pull request checklist

This PR has considered (when applicable):
- [ ] Automated Tests
- [ ] Documentation and examples
- [ ] Keyboard Accessibility
- [ ] Voiceover
- [ ] Internationalization and Right-to-left Layouts

### CODE REVIEW

File: packages/components/Stack/src/Stack.tsx [hunk 1]
```diff
@@ -28,11 +28,10 @@ const render = (Slots: ISlots<IStackSlotProps>, renderData: IStackRenderData, ..
...
       if (React.isValidElement(child) && index > 0) {
         const childProps = child.props;
-        const extraProps = { style: _mixinStyle(childProps[_styleKey], extraStyle) };
-        return React.cloneElement(child, {
-          ...childProps,
-          ...extraProps,
-        });
+        const mixedStyle = _mixinStyle(childProps[_styleKey], extraStyle);
+        const styleProp = Object.create({});
+        Object.defineProperty(styleProp, 'style', { value: mixedStyle, configurable: true });
```
Comment (Saadnajmi) [inline packages/components/Stack/src/Stack.tsx:33]: Nit: Maybe add a comment about why these two lines are needed with an issue # ?

**Review by Saadnajmi — APPROVED** [review]

File: packages/components/Stack/src/Stack.tsx (hunk 1 above)
Comment (rurikoaraki) [reply packages/components/Stack/src/Stack.tsx]: Solution has changed, since this actually didn't fix the bug.

File: packages/components/Stack/src/Stack.tsx [hunk 2]
```diff
@@ -21,7 +30,12 @@ const _styleKey = 'style';
 const render = (Slots: ISlots<IStackSlotProps>, renderData: IStackRenderData, ...children: React.ReactNode[]): JSX.Element => {
   const { gap, horizontal, wrap } = renderData.state!;
 
-  if (gap && gap > 0 && children) {
+  if (
+    gap &&
+    gap > 0 &&
+    children &&
+    (!global.hasOwnProperty('__jsiExecutorDescription') || global.__jsiExecutorDescription !== 'ChakraRuntime')
```
Comment (rurikoaraki) [inline packages/components/Stack/src/Stack.tsx:37]: TODO: Need to add a comment for this

Also fix the experimental Stack.

Comment (tido64) [reply packages/components/Stack/src/Stack.tsx:37]: `__jsiExecutorDescription` would just be `undefined` if it isn't set, so you can drop the first check:

```suggestion
    global.__jsiExecutorDescription !== 'ChakraRuntime'
```

Comment (rurikoaraki) [reply packages/components/Stack/src/Stack.tsx]: Thanks, change has been made.

**Review by Saadnajmi — APPROVED** [review]

**Review by tido64 — APPROVED** [review]
