### PR TITLE
Fix default theme failing when appearance not passed in

### LINKED ISSUE #1004: Issue with theme library causing test failures
### Environment Information

- **Package version(s)**:
```
    "@fluentui-react-native/apple-theme": "^0.7.23",
    "@fluentui-react-native/default-theme": "^0.8.3",
    "@fluentui-react-native/theme": "^0.5.19",
    "@fluentui-react-native/theme-types": "^0.12.1",
    "@fluentui-react-native/win32-theme": "^0.13.2",
    "@fluentui/react-native": "0.25.13",
```

- **Platform**:
all

### Please provide a reproduction of the bug:

when running a test 

```
    const theme = createDefaultTheme();

    const tree = renderer
      .create(
        <ThemeProvider theme={theme}>
          <Component>
        </ThemeProvider>,
      )
      .toJSON();
    expect(tree).toMatchSnapshot();
```

I get this error

```
    Unhandled discriminated union member: undefined

      at Object.assertNever (../../common/temp/node_modules/.pnpm/assert-never@1.2.1/node_modules/assert-never/index.js:32:11)
      at ../../common/temp/node_modules/.pnpm/@fluentui-react-native/default-theme@0.8.3_d1c53b50ef9cfe887d69c9bf99b2b704/node_modules/@fluentui-react-native/default-theme/src/createDefaultTheme.ts:19:20
      at ThemeReference.get [as theme] (../../common/temp/node_modules/.pnpm/@fluentui-react-native/theme@0.5.19_e6f6aee82b874cf5b3bad5d449c8dc73/node_modules/@fluentui-react-native/theme/src/themeReference.ts:61:66)
      at ../../common/temp/node_modules/.pnpm/@fluentui-react-native/theme@0.5.19_e6f6aee82b874cf5b3bad5d449c8dc73/node_modules/@fluentui-react-native/theme/src/ThemeProvider.tsx:14:9
      at mountState (../../common/temp/node_modules/.pnpm/react-test-renderer@16.13.1_react@16.13.1/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5971:20)
      at Object.useState (../../common/temp/node_modules/.pnpm/react-test-renderer@16.13.1_react@16.13.1/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6516:16)
      at Object.useState (../../common/temp/node_modules/.pnpm/react@16.13.1/node_modules/react/cjs/react.development.js:1497:21)
      at Object.<anonymous>.exports.ThemeProvider (../../common/temp/node_modules/.pnpm/@fluentui-react-native/theme@0.5.19_e6f6aee82b874cf5b3bad5d449c8dc73/node_modules/@fluentui-react-native/theme/src/ThemeProvider.tsx:14:9)
      at renderWithHooks (../../common/temp/node_modules/.pnpm/react-test-renderer@16.13.1_react@16.13.1/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5552:18)
      at mountIndeterminateComponent (../../common/temp/node_modules/.pnpm/react-test-renderer@16.13.1_react@16.13.1/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7918:13)

```

### Hypothesis
I think this might be some weird interaction of passing a partial theme to the theme provider,

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Blocking

Products/applications affected: (if applicable)
Excel Taskpane

### PR DESCRIPTION
**Pull request by rurikoaraki**
Fixes #1004 

### Platforms Impacted
- [ ] iOS
- [ ] macOS
- [x] win32 (Office)
- [x] windows
- [ ] android

### Description of changes

If a defined appearance is not passed in to getCurrentAppearance, it currently returns undefined.

Give a fallback if there's no appearance passed in as part of options.

### Verification

Tested change with Tester.

### Pull request checklist

This PR has considered (when applicable):
- [ ] Automated Tests
- [ ] Documentation and examples
- [ ] Keyboard Accessibility
- [ ] Voiceover
- [ ] Internationalization and Right-to-left Layouts

### CODE REVIEW

File: packages/theming/theming-utils/src/getCurrentAppearance.ts [hunk 1]
```diff
@@ -2,5 +2,9 @@ import { Appearance } from 'react-native';
 import { AppearanceOptions, ThemeOptions } from '@fluentui-react-native/theme-types';
 
 export function getCurrentAppearance(appearance: ThemeOptions['appearance'], fallback: AppearanceOptions): AppearanceOptions {
+  if (appearance === undefined) {
```
Comment (Saadnajmi) [inline packages/theming/theming-utils/src/getCurrentAppearance.ts:5]: nit: I think `if (!!appearance)` does the same thing as this?

**Review by Saadnajmi — APPROVED** [review]

File: packages/theming/theming-utils/src/getCurrentAppearance.ts (hunk 1 above)
Comment (rurikoaraki) [reply packages/theming/theming-utils/src/getCurrentAppearance.ts:5]: I think `if (!!appearance)` only runs if appearance is a non-falsy (since !appearance is true if appearance is falsy and false if truthy, and then !!appearance would be false if falsy and true if truthy)

1. I personally prefer having bail outs earlier in functions and then running the rest of the logic instead of wrapping the logic in an if statement, I find it cleaner since it's less nesting and easier to read
2. The === undefined just lets me be more specific that I'm trying to catch undefined specifically instead of all falsy values. I don't mind changing it to `if (!appearance)`, but I like being more precise.

Comment (Saadnajmi) [reply packages/theming/theming-utils/src/getCurrentAppearance.ts:5]: Thanks for the explanation, yeah that makes sense!
